; Sentinel Desktop v1.0.0 — Inno Setup Installer
; Generated by installer/build.py

#define MyAppName "SentinelDesktop"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "Sentinel Labs"
#define MyAppURL "https://github.com/dirtysouthalpha/sentinel-desktop"
#define MyAppExeName "SentinelDesktop.exe"

[Setup]
AppId={{8C2F4A6E-3B5D-4F7C-A9E1-1D0E6B8F2A45}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
OutputDir=/home/dad/Projects/sentinel-desktop/.pytest_tmp/test_generates_iss_file0/installer/output
OutputBaseFilename=SentinelDesktop-1.0.0-Setup
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin
UninstallDisplayName={#MyAppName}
SetupIconFile=

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"
Name: "startmenuicon"; Description: "Create Start Menu shortcut"; GroupDescription: "{cm:AdditionalIcons}"

[Files]
Source: "/home/dad/Projects/sentinel-desktop/.pytest_tmp/test_generates_iss_file0/dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "/home/dad/Projects/sentinel-desktop/.pytest_tmp/test_generates_iss_file0\config\*"; DestDir: "{app}\config"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "/home/dad/Projects/sentinel-desktop/.pytest_tmp/test_generates_iss_file0\scripts\*"; DestDir: "{app}\scripts"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "/home/dad/Projects/sentinel-desktop/.pytest_tmp/test_generates_iss_file0\plugins\*"; DestDir: "{app}\plugins"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#MyAppName}}"; Flags: nowait postinstall skipifsilent
