# -*- mode: python ; coding: utf-8 -*-
"""Sentinel Desktop Steel — PyInstaller spec (lean build)."""

import os

ROOT = os.path.abspath(SPECPATH)

a = Analysis(
    [os.path.join(ROOT, 'main.py')],
    pathex=[ROOT],
    binaries=[],
    datas=[
        ('gui/qml/*.qml', 'gui/qml'),
        ('gui/qml/*.py', 'gui/qml'),
        ('gui/bridge/*.py', 'gui/bridge'),
        ('config.py', '.'),
        ('core', 'core'),
        ('scripts', 'scripts'),
        ('plugins', 'plugins'),
    ],
    hiddenimports=[
        'gui.steel_launcher',
        'gui.bridge.controller',
        'gui.qml.image_provider',
        'gui.app',
        'gui.themes',
        'gui.overlay',
        'gui.tray',
        'gui.tabs.scripts_tab',
        'gui.tabs.workflows_tab',
        'gui.tabs.memory_tab',
        'gui.tabs.history_tab',
        'gui.tabs.settings_tab',
        'core.engine',
        'core.llm_client',
        'core.action_executor',
        'core.desktop',
        'core.screenshot',
        'core.window_manager',
        'core.process_manager',
        'core.clipboard',
        'core.file_ops',
        'core.system_info',
        'core.provider_registry',
        'core.recovery',
        'core.scheduler',
        'core.auth',
        'core.encryption',
        'core.popup_handler',
        'core.config_store',
        'core.net_tools',
        'core.window_control',
        'core.http_client',
        'core.file_watcher',
        'core.audio',
        'core.checkpoint',
        'core.perception',
        'core.platform',
        'core.platform.base',
        'core.platform.windows_backend',
        'core.web',
        'core.netops',
        'core.server',
        'core.memory',
        'core.conductor',
        'core.swarm',
        'core.control',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'torch', 'torchvision', 'torchaudio',
        'scipy', 'numpy', 'pandas', 'matplotlib',
        'tkinter', 'test', 'unittest',
        'pytest', 'py.test', '_pytest',
        'IPython', 'ipykernel', 'jupyter',
        'notebook', 'nbconvert',
        'PIL', 'pillow',
        'cv2', 'opencv',
        'sklearn', 'scikit-learn',
        'seaborn', 'plotly',
        'bokeh', 'altair',
        'pyarrow', 'numba', 'llvmlite',
        'openai', 'anthropic', 'google', 'transformers',
        'huggingface', 'datasets', 'tokenizers',
        'safetensors', 'accelerate',
        'tensorboard', 'tensorboardX',
        'onnx', 'onnxruntime',
        'nvidia', 'cuda',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='SentinelDesktop',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='SentinelDesktop',
)
