"""
Sentinel Desktop v30.0.0 — Theme definitions for CustomTkinter.

19 built-in themes. Default "sentinel" matches Sentinel Override's
cyberpunk HUD exactly (cyan #00F0FF, near-black #050608, lime/amber).
Override-exclusive presets: Matrix, Tron, Cyberpunk, Neon, Terminal,
Blood, Ember, Frost, Phantom.
"""

from __future__ import annotations

import logging
from typing import Any

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Color palette constants
# ---------------------------------------------------------------------------
THEMES: dict[str, dict[str, Any]] = {
    # ── Sentinel (default) — Override Cyberpunk HUD ────────────────────
    #    Matches sentinel-override/popup.css design tokens exactly.
    #    Cyan neon #00F0FF, near-black surfaces, lime/amber accents.
    "sentinel": {
        "label": "🛡️ Sentinel",
        "appearance": "dark",
        "color_theme": "dark-blue",
        "accent": "#00F0FF",
        "accent_hover": "#00c8d4",
        "bg_primary": "#050608",
        "bg_secondary": "#0A0C10",
        "bg_input": "#111418",
        "bg_hover": "#333539",
        "text_primary": "#e2e2e8",
        "text_secondary": "#b9cacb",
        "status_idle": "#849495",
        "status_running": "#95E400",
        "status_error": "#ff3b3b",
        "tag_user": "#00F0FF",
        "tag_assistant": "#95E400",
        "tag_action": "#FBBC00",
        "tag_error": "#ff3b3b",
        "tag_system": "#849495",
        "overlay_ring": "#00F0FF",
        "overlay_fill": "#00F0FF",
        "border_color": "#3b494b",
        "border_active": "#00F0FF",
    },
    # ── Dark family ─────────────────────────────────────────────────────
    "midnight": {
        "label": "🌌 Midnight",
        "appearance": "dark",
        "color_theme": "dark-blue",
        "accent": "#4A90D9",
        "accent_hover": "#5BA0E9",
        "bg_primary": "#1a1a2e",
        "bg_secondary": "#16213e",
        "bg_input": "#0f3460",
        "bg_hover": "#1e2e52",
        "text_primary": "#e0e0e0",
        "text_secondary": "#a0a0b0",
        "status_idle": "#666666",
        "status_running": "#2ecc71",
        "status_error": "#e74c3c",
        "tag_user": "#4A90D9",
        "tag_assistant": "#2ecc71",
        "tag_action": "#f39c12",
        "tag_error": "#e74c3c",
        "tag_system": "#95a5a6",
        "overlay_ring": "#4A90D9",
        "overlay_fill": "#4A90D9",
    },
    "dark": {
        "label": "🌙 Dark",
        "appearance": "dark",
        "color_theme": "dark-blue",
        "accent": "#1f6aa5",
        "accent_hover": "#2a7abf",
        "bg_primary": "#2b2b2b",
        "bg_secondary": "#333333",
        "bg_input": "#404040",
        "bg_hover": "#444444",
        "text_primary": "#d0d0d0",
        "text_secondary": "#909090",
        "status_idle": "#666666",
        "status_running": "#2ecc71",
        "status_error": "#e74c3c",
        "tag_user": "#1f6aa5",
        "tag_assistant": "#2ecc71",
        "tag_action": "#f39c12",
        "tag_error": "#e74c3c",
        "tag_system": "#808080",
        "overlay_ring": "#1f6aa5",
        "overlay_fill": "#1f6aa5",
    },
    "matrix": {
        "label": "💻 Matrix",
        "appearance": "dark",
        "color_theme": "dark-blue",
        "accent": "#00ff41",
        "accent_hover": "#33ff66",
        "bg_primary": "#050608",
        "bg_secondary": "#0A0C10",
        "bg_input": "#0f1a0f",
        "bg_hover": "#1a3a1a",
        "text_primary": "#00ff41",
        "text_secondary": "#009926",
        "status_idle": "#004d00",
        "status_running": "#00ff41",
        "status_error": "#ff0000",
        "tag_user": "#00ff41",
        "tag_assistant": "#33ff66",
        "tag_action": "#99ff99",
        "tag_error": "#ff3333",
        "tag_system": "#00802b",
        "overlay_ring": "#00ff41",
        "overlay_fill": "#00ff41",
        "border_color": "#1a3a1a",
        "border_active": "#00ff41",
    },
    "tron": {
        "label": "🔷 Tron",
        "appearance": "dark",
        "color_theme": "dark-blue",
        "accent": "#00d4ff",
        "accent_hover": "#33e8ff",
        "bg_primary": "#050608",
        "bg_secondary": "#0A0C10",
        "bg_input": "#101c2a",
        "bg_hover": "#182535",
        "text_primary": "#c0e8ff",
        "text_secondary": "#5a8aa5",
        "status_idle": "#2a4a5a",
        "status_running": "#00d4ff",
        "status_error": "#ff3366",
        "tag_user": "#00d4ff",
        "tag_assistant": "#66eeff",
        "tag_action": "#ffaa00",
        "tag_error": "#ff3366",
        "tag_system": "#3a6a8a",
        "overlay_ring": "#00d4ff",
        "overlay_fill": "#00d4ff",
        "border_color": "#2a4a5a",
        "border_active": "#00d4ff",
    },
    "cyberpunk": {
        "label": "⚡ Cyberpunk",
        "appearance": "dark",
        "color_theme": "dark-blue",
        "accent": "#ff2a6d",
        "accent_hover": "#ff5588",
        "bg_primary": "#050608",
        "bg_secondary": "#0A0C10",
        "bg_input": "#1a0018",
        "bg_hover": "#280040",
        "text_primary": "#ff2a6d",
        "text_secondary": "#cc2288",
        "status_idle": "#660033",
        "status_running": "#05d9e8",
        "status_error": "#ff2a6d",
        "tag_user": "#ff2a6d",
        "tag_assistant": "#05d9e8",
        "tag_action": "#f5dd42",
        "tag_error": "#ff2a6d",
        "tag_system": "#770044",
        "overlay_ring": "#ff2a6d",
        "overlay_fill": "#ff2a6d",
        "border_color": "#3b494b",
        "border_active": "#ff2a6d",
    },
    "neon": {
        "label": "💜 Neon",
        "appearance": "dark",
        "color_theme": "dark-blue",
        "accent": "#e040fb",
        "accent_hover": "#cc33ff",
        "bg_primary": "#050608",
        "bg_secondary": "#0A0C10",
        "bg_input": "#1f0033",
        "bg_hover": "#280045",
        "text_primary": "#e0b0ff",
        "text_secondary": "#9966cc",
        "status_idle": "#4d0080",
        "status_running": "#e040fb",
        "status_error": "#ff0066",
        "tag_user": "#e040fb",
        "tag_assistant": "#cc66ff",
        "tag_action": "#ff9900",
        "tag_error": "#ff0066",
        "tag_system": "#6633cc",
        "overlay_ring": "#e040fb",
        "overlay_fill": "#e040fb",
        "border_color": "#3b494b",
        "border_active": "#e040fb",
    },
    "terminal": {
        "label": "🟢 Terminal",
        "appearance": "dark",
        "color_theme": "dark-blue",
        "accent": "#33ff33",
        "accent_hover": "#66ff66",
        "bg_primary": "#000000",
        "bg_secondary": "#0A0C10",
        "bg_input": "#141414",
        "bg_hover": "#1e1e1e",
        "text_primary": "#33ff33",
        "text_secondary": "#008800",
        "status_idle": "#004400",
        "status_running": "#33ff33",
        "status_error": "#ff0000",
        "tag_user": "#33ff33",
        "tag_assistant": "#44ff44",
        "tag_action": "#ffff00",
        "tag_error": "#ff0000",
        "tag_system": "#006600",
        "overlay_ring": "#33ff33",
        "overlay_fill": "#33ff33",
        "border_color": "#004400",
        "border_active": "#33ff33",
    },
    "blood": {
        "label": "🩸 Blood",
        "appearance": "dark",
        "color_theme": "dark-blue",
        "accent": "#ff1a1a",
        "accent_hover": "#ff3333",
        "bg_primary": "#050608",
        "bg_secondary": "#0A0C10",
        "bg_input": "#200000",
        "bg_hover": "#2a0000",
        "text_primary": "#ff3333",
        "text_secondary": "#993333",
        "status_idle": "#4d0000",
        "status_running": "#ff1a1a",
        "status_error": "#ff0000",
        "tag_user": "#ff1a1a",
        "tag_assistant": "#ff4444",
        "tag_action": "#ff8800",
        "tag_error": "#ff0000",
        "tag_system": "#660000",
        "overlay_ring": "#ff1a1a",
        "overlay_fill": "#ff1a1a",
        "border_color": "#3b494b",
        "border_active": "#ff1a1a",
    },
    "ocean": {
        "label": "🌊 Ocean",
        "appearance": "dark",
        "color_theme": "blue",
        "accent": "#0077be",
        "accent_hover": "#0088dd",
        "bg_primary": "#001122",
        "bg_secondary": "#001a33",
        "bg_input": "#002244",
        "bg_hover": "#002a50",
        "text_primary": "#c0ddef",
        "text_secondary": "#5a8ea8",
        "status_idle": "#003355",
        "status_running": "#00aaff",
        "status_error": "#ff4444",
        "tag_user": "#0077be",
        "tag_assistant": "#00aaff",
        "tag_action": "#ffbb33",
        "tag_error": "#ff4444",
        "tag_system": "#336688",
        "overlay_ring": "#0077be",
        "overlay_fill": "#0077be",
    },
    # ── Override-exclusive presets (from popup.css body.theme-*) ──────
    "ember": {
        "label": "🔥 Ember",
        "appearance": "dark",
        "color_theme": "dark-blue",
        "accent": "#ff7a45",
        "accent_hover": "#ff9966",
        "bg_primary": "#050608",
        "bg_secondary": "#0A0C10",
        "bg_input": "#1a0f05",
        "bg_hover": "#2a1505",
        "text_primary": "#ffd4b8",
        "text_secondary": "#e89e7a",
        "status_idle": "#663300",
        "status_running": "#ff7a45",
        "status_error": "#ff3b3b",
        "tag_user": "#ff7a45",
        "tag_assistant": "#ffaa44",
        "tag_action": "#FBBC00",
        "tag_error": "#ff3b3b",
        "tag_system": "#b87a5c",
        "overlay_ring": "#ff7a45",
        "overlay_fill": "#ff7a45",
        "border_color": "#3b494b",
        "border_active": "#ff7a45",
    },
    "frost": {
        "label": "❄️ Frost",
        "appearance": "dark",
        "color_theme": "dark-blue",
        "accent": "#00b8d4",
        "accent_hover": "#33ccdd",
        "bg_primary": "#050608",
        "bg_secondary": "#0A0C10",
        "bg_input": "#0a1520",
        "bg_hover": "#152030",
        "text_primary": "#c0e8ff",
        "text_secondary": "#98c8e8",
        "status_idle": "#1a3a4a",
        "status_running": "#00b8d4",
        "status_error": "#ff3b3b",
        "tag_user": "#00b8d4",
        "tag_assistant": "#66ddff",
        "tag_action": "#FBBC00",
        "tag_error": "#ff3b3b",
        "tag_system": "#5e8ba8",
        "overlay_ring": "#00b8d4",
        "overlay_fill": "#00b8d4",
        "border_color": "#3b494b",
        "border_active": "#00b8d4",
    },
    "phantom": {
        "label": "👻 Phantom",
        "appearance": "dark",
        "color_theme": "dark-blue",
        "accent": "#8a5cff",
        "accent_hover": "#a077ff",
        "bg_primary": "#050608",
        "bg_secondary": "#0A0C10",
        "bg_input": "#15102a",
        "bg_hover": "#201a35",
        "text_primary": "#c8c0e8",
        "text_secondary": "#a8a0d8",
        "status_idle": "#2a2255",
        "status_running": "#8a5cff",
        "status_error": "#ff3b3b",
        "tag_user": "#8a5cff",
        "tag_assistant": "#aa88ff",
        "tag_action": "#FBBC00",
        "tag_error": "#ff3b3b",
        "tag_system": "#6a6298",
        "overlay_ring": "#8a5cff",
        "overlay_fill": "#8a5cff",
        "border_color": "#3b494b",
        "border_active": "#8a5cff",
    },
    # ── Light / warm family ─────────────────────────────────────────────
    "light": {
        "label": "☀️ Light",
        "appearance": "light",
        "color_theme": "blue",
        "accent": "#1f6aa5",
        "accent_hover": "#2a7abf",
        "bg_primary": "#f0f0f0",
        "bg_secondary": "#e0e0e0",
        "bg_input": "#ffffff",
        "bg_hover": "#d0d0d0",
        "text_primary": "#222222",
        "text_secondary": "#666666",
        "status_idle": "#999999",
        "status_running": "#2ecc71",
        "status_error": "#e74c3c",
        "tag_user": "#1f6aa5",
        "tag_assistant": "#27ae60",
        "tag_action": "#e67e22",
        "tag_error": "#e74c3c",
        "tag_system": "#888888",
        "overlay_ring": "#1f6aa5",
        "overlay_fill": "#1f6aa5",
    },
    "sunset": {
        "label": "🌅 Sunset",
        "appearance": "dark",
        "color_theme": "dark-blue",
        "accent": "#ff6b35",
        "accent_hover": "#ff8855",
        "bg_primary": "#1a0a00",
        "bg_secondary": "#2a1500",
        "bg_input": "#3a2000",
        "bg_hover": "#4a2a00",
        "text_primary": "#ffd4b8",
        "text_secondary": "#b07040",
        "status_idle": "#663300",
        "status_running": "#ff6b35",
        "status_error": "#ff3333",
        "tag_user": "#ff6b35",
        "tag_assistant": "#ffaa44",
        "tag_action": "#ffdd00",
        "tag_error": "#ff3333",
        "tag_system": "#884422",
        "overlay_ring": "#ff6b35",
        "overlay_fill": "#ff6b35",
    },
    "paper": {
        "label": "📜 Paper",
        "appearance": "light",
        "color_theme": "blue",
        "accent": "#8b7355",
        "accent_hover": "#a08866",
        "bg_primary": "#f5f0e8",
        "bg_secondary": "#ebe5d8",
        "bg_input": "#ffffff",
        "bg_hover": "#ddd5c8",
        "text_primary": "#3a3226",
        "text_secondary": "#7a6e5e",
        "status_idle": "#b0a890",
        "status_running": "#6b8e4e",
        "status_error": "#c44",
        "tag_user": "#8b7355",
        "tag_assistant": "#6b8e4e",
        "tag_action": "#b8860b",
        "tag_error": "#c44",
        "tag_system": "#9a8e7e",
        "overlay_ring": "#8b7355",
        "overlay_fill": "#8b7355",
    },
    "forest": {
        "label": "🌲 Forest",
        "appearance": "dark",
        "color_theme": "dark-blue",
        "accent": "#2d6a4f",
        "accent_hover": "#3a8a66",
        "bg_primary": "#0a1208",
        "bg_secondary": "#0f1a0c",
        "bg_input": "#142210",
        "bg_hover": "#1a2e16",
        "text_primary": "#a8d5a0",
        "text_secondary": "#5a8a50",
        "status_idle": "#2a4a22",
        "status_running": "#52b788",
        "status_error": "#e74c3c",
        "tag_user": "#2d6a4f",
        "tag_assistant": "#52b788",
        "tag_action": "#d4a037",
        "tag_error": "#e74c3c",
        "tag_system": "#3a5a32",
        "overlay_ring": "#2d6a4f",
        "overlay_fill": "#2d6a4f",
    },
    "mono": {
        "label": "⬛ Mono",
        "appearance": "dark",
        "color_theme": "dark-blue",
        "accent": "#cccccc",
        "accent_hover": "#ffffff",
        "bg_primary": "#111111",
        "bg_secondary": "#1a1a1a",
        "bg_input": "#222222",
        "bg_hover": "#2a2a2a",
        "text_primary": "#cccccc",
        "text_secondary": "#777777",
        "status_idle": "#444444",
        "status_running": "#ffffff",
        "status_error": "#ff4444",
        "tag_user": "#cccccc",
        "tag_assistant": "#ffffff",
        "tag_action": "#999999",
        "tag_error": "#ff4444",
        "tag_system": "#555555",
        "overlay_ring": "#cccccc",
        "overlay_fill": "#cccccc",
    },
}


def get_theme(name: str) -> dict[str, Any]:
    """Get a theme by name, falling back to sentinel."""
    return THEMES.get(name, THEMES["sentinel"])


def get_theme_names() -> list[tuple[str, str]]:
    """Return list of (key, label) tuples for all themes."""
    return [(k, v["label"]) for k, v in THEMES.items()]


def apply_theme(name_or_dict: str | dict[str, Any]) -> dict[str, Any]:
    """Apply a named theme or theme dict to customtkinter. Returns the theme dict."""
    try:
        import customtkinter as ctk
    except ImportError:
        return THEMES["sentinel"]

    theme = THEMES.get(name_or_dict, THEMES["sentinel"]) if isinstance(name_or_dict, str) else name_or_dict

    ctk.set_appearance_mode(theme.get("appearance", "dark"))
    ctk.set_default_color_theme(theme.get("color_theme", "dark-blue"))

    return theme
