"""
Sentinel Desktop — Build Script
PyInstaller EXE builder + Inno Setup installer generator.

Usage:
    python installer/build.py --exe        # Build standalone EXE
    python installer/build.py --installer  # Generate Inno Setup .iss
    python installer/build.py --all        # Build everything
    python installer/build.py --clean      # Remove build artifacts
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys

# Make the project root importable so we can read core.__version__.
_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

from core import __version__ as APP_VERSION  # noqa: E402

# ── Config ──────────────────────────────────────────────────────────────

APP_NAME = "SentinelDesktop"
APP_PUBLISHER = "Sentinel Labs"
APP_URL = "https://github.com/dirtysouthalpha/sentinel-desktop"
# Stable GUID for Inno Setup upgrade detection. Must NOT change across versions.
APP_GUID = "8C2F4A6E-3B5D-4F7C-A9E1-1D0E6B8F2A45"

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DIST_DIR = os.path.join(ROOT_DIR, "dist")
BUILD_DIR = os.path.join(ROOT_DIR, "build")
SPEC_FILE = os.path.join(ROOT_DIR, f"{APP_NAME}.spec")
ICON_PATH = os.path.join(ROOT_DIR, "assets", "icon.ico")
INSTALLER_DIR = os.path.join(ROOT_DIR, "installer")

HIDDEN_IMPORTS = [
    "core.engine",
    "core.action_executor",
    "core.screenshot",
    "core.llm_client",
    "core.forensic_log",
    "core.checkpoint",
    "core.smart_wait",
    "core.mfa_detection",
    "core.system_info",
    "core.window_manager",
    "core.virtual_desktop",
    "core.failsafe",
    "core.recorder",
    "core.script_engine",
    "core.powershell",
    "core.workflow",
    "core.scheduler",
    "core.notifications",
    "core.plugin_loader",
    "core.auth",
    "core.encryption",
    "core.audit_export",
    "core.command_palette",
    "core.provider_registry",
    "core.tool_schemas",
    "gui.app",
    "gui.themes",
    "gui.recorder_panel",
    "gui.tabs.scripts_tab",
    "gui.tabs.workflows_tab",
    "gui.tabs.history_tab",
    "gui.tabs.settings_tab",
    "gui.system_tray",
    "api.server",
    "customtkinter",
    "PIL",
    "pystray",
]


def clean() -> None:
    """Remove build artifacts."""
    for path in [BUILD_DIR, DIST_DIR]:
        if os.path.exists(path):
            shutil.rmtree(path)
            print(f"  Removed {path}")
    if os.path.exists(SPEC_FILE):
        os.remove(SPEC_FILE)
        print(f"  Removed {SPEC_FILE}")
    print("✅ Clean complete")


def build_exe() -> bool:
    """Build standalone Windows EXE via PyInstaller."""
    print(f"🔨 Building {APP_NAME} v{APP_VERSION}...")

    try:
        import PyInstaller  # noqa: F401
    except ImportError:
        print("❌ PyInstaller not installed. Run: pip install pyinstaller")
        return False

    cmd = [
        sys.executable,
        "-m",
        "PyInstaller",
        "--name",
        APP_NAME,
        "--windowed",
        "--onefile",
        "--noconfirm",
    ]

    if os.path.exists(ICON_PATH):
        cmd.extend(["--icon", ICON_PATH])
        print(f"  Icon: {ICON_PATH}")

    # Add data directories
    for data_dir in ["config", "scripts", "plugins", "assets"]:
        src = os.path.join(ROOT_DIR, data_dir)
        if os.path.exists(src):
            cmd.extend(["--add-data", f"{src};{data_dir}"])
            print(f"  Data: {data_dir}/")

    # Hidden imports
    for imp in HIDDEN_IMPORTS:
        cmd.extend(["--hidden-import", imp])

    # UPX compression
    upx_path = shutil.which("upx")
    if upx_path:
        cmd.extend(["--upx-dir", os.path.dirname(upx_path)])
        print(f"  UPX: {upx_path}")

    cmd.extend(
        [
            "--distpath",
            DIST_DIR,
            "--workpath",
            BUILD_DIR,
            "--specpath",
            ROOT_DIR,
            os.path.join(ROOT_DIR, "main.py"),
        ]
    )

    print("  Running PyInstaller...")
    result = subprocess.run(cmd, cwd=ROOT_DIR)

    if result.returncode == 0:
        exe_path = os.path.join(DIST_DIR, f"{APP_NAME}.exe")
        if os.path.exists(exe_path):
            size_mb = os.path.getsize(exe_path) / (1024 * 1024)
            print(f"✅ Built: {exe_path} ({size_mb:.1f} MB)")
            return True
    print(f"❌ Build failed (exit {result.returncode})")
    return False


def generate_inno_setup() -> str:
    """Generate Inno Setup .iss file for Windows installer."""
    print("📜 Generating Inno Setup script...")

    iss_content = f"""; Sentinel Desktop v{APP_VERSION} — Inno Setup Installer
; Generated by installer/build.py

#define MyAppName "{APP_NAME}"
#define MyAppVersion "{APP_VERSION}"
#define MyAppPublisher "{APP_PUBLISHER}"
#define MyAppURL "{APP_URL}"
#define MyAppExeName "{APP_NAME}.exe"

[Setup]
AppId={{{{{APP_GUID}}}}}
AppName={{#MyAppName}}
AppVersion={{#MyAppVersion}}
AppVerName={{#MyAppName}} {{#MyAppVersion}}
AppPublisher={{#MyAppPublisher}}
AppPublisherURL={{#MyAppURL}}
AppSupportURL={{#MyAppURL}}
DefaultDirName={{autopf}}\\{{#MyAppName}}
DefaultGroupName={{#MyAppName}}
AllowNoIcons=yes
OutputDir={os.path.join(INSTALLER_DIR, "output")}
OutputBaseFilename=SentinelDesktop-{APP_VERSION}-Setup
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin
UninstallDisplayName={{#MyAppName}}
SetupIconFile={ICON_PATH if os.path.exists(ICON_PATH) else ""}

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{{cm:CreateDesktopIcon}}"; GroupDescription: "{{cm:AdditionalIcons}}"
Name: "startmenuicon"; Description: "Create Start Menu shortcut"; GroupDescription: "{{cm:AdditionalIcons}}"

[Files]
Source: "{DIST_DIR}\\{{#MyAppExeName}}"; DestDir: "{{app}}"; Flags: ignoreversion
Source: "{ROOT_DIR}\\config\\*"; DestDir: "{{app}}\\config"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{ROOT_DIR}\\scripts\\*"; DestDir: "{{app}}\\scripts"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{ROOT_DIR}\\plugins\\*"; DestDir: "{{app}}\\plugins"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{{group}}\\{{#MyAppName}}"; Filename: "{{app}}\\{{#MyAppExeName}}"
Name: "{{group}}\\{{cm:UninstallProgram,{{#MyAppName}}}}"; Filename: "{{uninstallexe}}"
Name: "{{autodesktop}}\\{{#MyAppName}}"; Filename: "{{app}}\\{{#MyAppExeName}}"; Tasks: desktopicon

[Run]
Filename: "{{app}}\\{{#MyAppExeName}}"; Description: "{{cm:LaunchProgram,{{#MyAppName}}}}"; Flags: nowait postinstall skipifsilent
"""
    iss_path = os.path.join(INSTALLER_DIR, "sentinel-desktop.iss")
    os.makedirs(INSTALLER_DIR, exist_ok=True)
    with open(iss_path, "w", encoding="utf-8") as f:
        f.write(iss_content)

    print(f"✅ Generated: {iss_path}")
    return iss_path


def build_all() -> bool:
    """Build EXE then generate installer."""
    if not build_exe():
        return False
    iss_path = generate_inno_setup()
    print("\n🚀 Next step: compile the installer with Inno Setup:")
    print(f'   ISCC.exe "{iss_path}"')
    return True


def main() -> None:
    parser = argparse.ArgumentParser(description="Sentinel Desktop Build System")
    parser.add_argument("--exe", action="store_true", help="Build standalone EXE")
    parser.add_argument("--installer", action="store_true", help="Generate Inno Setup .iss")
    parser.add_argument("--all", action="store_true", help="Build everything")
    parser.add_argument("--clean", action="store_true", help="Remove build artifacts")
    args = parser.parse_args()

    if not any(vars(args).values()):
        parser.print_help()
        return

    if args.clean:
        clean()
    if args.exe:
        build_exe()
    if args.installer:
        generate_inno_setup()
    if args.all:
        build_all()


if __name__ == "__main__":
    main()
