"""
Sentinel Desktop — Build Script
PyInstaller EXE builder + Inno Setup installer generator.

Usage:
    python installer/build.py --exe        # Build standalone EXE
    python installer/build.py --installer  # Generate Inno Setup .iss
    python installer/build.py --all        # Build everything
    python installer/build.py --clean      # Remove build artifacts
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

# Make the project root importable so we can read core.__version__.
_ROOT = str(Path(__file__).resolve().parent.parent)
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

from core import __version__ as APP_VERSION  # noqa: E402

# ── Config ──────────────────────────────────────────────────────────────

APP_NAME = "SentinelDesktop"
APP_PUBLISHER = "Sentinel Labs"
APP_URL = "https://github.com/dirtysouthalpha/sentinel-desktop"
# Stable GUID for Inno Setup upgrade detection. Must NOT change across versions.
APP_GUID = "8C2F4A6E-3B5D-4F7C-A9E1-1D0E6B8F2A45"

ROOT_DIR = Path(__file__).resolve().parent.parent
DIST_DIR = ROOT_DIR / "dist"
BUILD_DIR = ROOT_DIR / "build"
SPEC_FILE = ROOT_DIR / f"{APP_NAME}.spec"
ICON_PATH = ROOT_DIR / "assets" / "icon.ico"
INSTALLER_DIR = ROOT_DIR / "installer"

HIDDEN_IMPORTS = [
    "core.engine",
    "core.action_executor",
    "core.screenshot",
    "core.llm_client",
    "core.forensic_log",
    "core.checkpoint",
    "core.smart_wait",
    "core.mfa_detection",
    "core.system_info",
    "core.window_manager",
    "core.virtual_desktop",
    "core.failsafe",
    "core.recorder",
    "core.script_engine",
    "core.powershell",
    "core.workflow",
    "core.scheduler",
    "core.notifications",
    "core.plugin_loader",
    "core.auth",
    "core.encryption",
    "core.audit_export",
    "core.command_palette",
    "core.provider_registry",
    "core.tool_schemas",
    "gui.app",
    "gui.themes",
    "gui.recorder_panel",
    "gui.tabs.scripts_tab",
    "gui.tabs.workflows_tab",
    "gui.tabs.history_tab",
    "gui.tabs.settings_tab",
    "gui.system_tray",
    "api.server",
    "customtkinter",
    "PIL",
    "pystray",
]


def clean() -> None:
    """Remove build artifacts."""
    for path in [BUILD_DIR, DIST_DIR]:
        if path.exists():
            try:
                shutil.rmtree(path)
                print(f"  Removed {path}")
            except OSError as exc:
                print(f"  ⚠ Could not remove {path}: {exc}")
    if SPEC_FILE.exists():
        try:
            SPEC_FILE.unlink()
            print(f"  Removed {SPEC_FILE}")
        except OSError as exc:
            print(f"  ⚠ Could not remove {SPEC_FILE}: {exc}")
    print("✅ Clean complete")


def build_exe() -> bool:
    """Build standalone Windows EXE via PyInstaller."""
    print(f"🔨 Building {APP_NAME} v{APP_VERSION}...")

    try:
        import PyInstaller  # noqa: F401
    except ImportError:
        print("❌ PyInstaller not installed. Run: pip install pyinstaller")
        return False

    cmd = [
        sys.executable,
        "-m",
        "PyInstaller",
        "--name",
        APP_NAME,
        "--windowed",
        "--onefile",
        "--noconfirm",
    ]

    if ICON_PATH.exists():
        cmd.extend(["--icon", str(ICON_PATH)])
        print(f"  Icon: {ICON_PATH}")

    # Add data directories
    for data_dir in ["config", "scripts", "plugins", "assets"]:
        src = ROOT_DIR / data_dir
        if src.exists():
            cmd.extend(["--add-data", f"{src};{data_dir}"])
            print(f"  Data: {data_dir}/")

    # Hidden imports
    for imp in HIDDEN_IMPORTS:
        cmd.extend(["--hidden-import", imp])

    # UPX compression
    upx_path = shutil.which("upx")
    if upx_path:
        cmd.extend(["--upx-dir", str(Path(upx_path).parent)])
        print(f"  UPX: {upx_path}")

    cmd.extend(
        [
            "--distpath",
            str(DIST_DIR),
            "--workpath",
            str(BUILD_DIR),
            "--specpath",
            str(ROOT_DIR),
            str(ROOT_DIR / "main.py"),
        ]
    )

    print("  Running PyInstaller...")
    try:
        result = subprocess.run(cmd, cwd=str(ROOT_DIR))
    except (OSError, subprocess.SubprocessError) as exc:
        print(f"❌ PyInstaller invocation failed: {exc}")
        return False

    if result.returncode == 0:
        exe_path = DIST_DIR / f"{APP_NAME}.exe"
        if exe_path.exists():
            size_mb = exe_path.stat().st_size / (1024 * 1024)
            print(f"✅ Built: {exe_path} ({size_mb:.1f} MB)")
            return True
    print(f"❌ Build failed (exit {result.returncode})")
    return False


def generate_inno_setup() -> str:
    """Generate Inno Setup .iss file for Windows installer."""
    print("📜 Generating Inno Setup script...")

    iss_content = f"""; Sentinel Desktop v{APP_VERSION} — Inno Setup Installer
; Generated by installer/build.py

#define MyAppName "{APP_NAME}"
#define MyAppVersion "{APP_VERSION}"
#define MyAppPublisher "{APP_PUBLISHER}"
#define MyAppURL "{APP_URL}"
#define MyAppExeName "{APP_NAME}.exe"

[Setup]
AppId={{{{{APP_GUID}}}}}
AppName={{#MyAppName}}
AppVersion={{#MyAppVersion}}
AppVerName={{#MyAppName}} {{#MyAppVersion}}
AppPublisher={{#MyAppPublisher}}
AppPublisherURL={{#MyAppURL}}
AppSupportURL={{#MyAppURL}}
DefaultDirName={{autopf}}\\{{#MyAppName}}
DefaultGroupName={{#MyAppName}}
AllowNoIcons=yes
OutputDir={INSTALLER_DIR / "output"}
OutputBaseFilename=SentinelDesktop-{APP_VERSION}-Setup
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin
UninstallDisplayName={{#MyAppName}}
SetupIconFile={ICON_PATH if ICON_PATH.exists() else ""}

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{{cm:CreateDesktopIcon}}"; GroupDescription: "{{cm:AdditionalIcons}}"
Name: "startmenuicon"; Description: "Create Start Menu shortcut"; GroupDescription: "{{cm:AdditionalIcons}}"

[Files]
Source: "{DIST_DIR}\\{{#MyAppExeName}}"; DestDir: "{{app}}"; Flags: ignoreversion
Source: "{ROOT_DIR}\\config\\*"; DestDir: "{{app}}\\config"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{ROOT_DIR}\\scripts\\*"; DestDir: "{{app}}\\scripts"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{ROOT_DIR}\\plugins\\*"; DestDir: "{{app}}\\plugins"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{{group}}\\{{#MyAppName}}"; Filename: "{{app}}\\{{#MyAppExeName}}"
Name: "{{group}}\\{{cm:UninstallProgram,{{#MyAppName}}}}"; Filename: "{{uninstallexe}}"
Name: "{{autodesktop}}\\{{#MyAppName}}"; Filename: "{{app}}\\{{#MyAppExeName}}"; Tasks: desktopicon

[Run]
Filename: "{{app}}\\{{#MyAppExeName}}"; Description: "{{cm:LaunchProgram,{{#MyAppName}}}}"; Flags: nowait postinstall skipifsilent
"""
    iss_path = INSTALLER_DIR / "sentinel-desktop.iss"
    try:
        INSTALLER_DIR.mkdir(parents=True, exist_ok=True)
        with iss_path.open("w", encoding="utf-8") as f:
            f.write(iss_content)
    except OSError as exc:
        print(f"❌ Failed to write .iss file: {exc}")
        return ""

    print(f"✅ Generated: {iss_path}")
    return str(iss_path)


def build_all() -> bool:
    """Build EXE then generate installer."""
    if not build_exe():
        return False
    iss_path = generate_inno_setup()
    print("\n🚀 Next step: compile the installer with Inno Setup:")
    print(f'   ISCC.exe "{iss_path}"')
    return True


def main() -> None:
    """Parse build-system CLI arguments and run requested build steps."""
    parser = argparse.ArgumentParser(description="Sentinel Desktop Build System")
    parser.add_argument("--exe", action="store_true", help="Build standalone EXE")
    parser.add_argument("--installer", action="store_true", help="Generate Inno Setup .iss")
    parser.add_argument("--all", action="store_true", help="Build everything")
    parser.add_argument("--clean", action="store_true", help="Remove build artifacts")
    args = parser.parse_args()

    if not any(vars(args).values()):
        parser.print_help()
        return

    if args.clean:
        clean()
    if args.exe:
        build_exe()
    if args.installer:
        generate_inno_setup()
    if args.all:
        build_all()


if __name__ == "__main__":
    main()
